name: noir
base: core20
version: 0.23.0
summary: Attack surface detector that identifies endpoints by static analysis.
description: |
  Noir is an open-source project specializing in identifying attack surfaces for enhanced whitebox security testing and security pipeline.
  This includes the capability to discover API endpoints, web endpoints, and other potential entry points within source code for thorough security analysis.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: MIT

apps:
  noir:
    command: noir

parts:
  noir:
    source: ./
    plugin: nil #crystal
    #crystal-channel: latest/stable
    override-build: |
      curl -fsSL https://crystal-lang.org/install.sh | sudo bash
      snapcraftctl pull
      shards install
      shards build --release --no-debug --production
      cp ./bin/noir $SNAPCRAFT_PART_INSTALL/
      snapcraftctl build
    build-packages:
      - git
      - curl
      - libssl-dev
      - libxml2-dev
      - libz-dev
      - libyaml-dev
      - libpcre2-dev
      - libevent-dev
      - libgmp-dev
    stage-packages:
      - libssl1.1
      - libxml2
      - libevent-2.1-7
