name: noir
base: core20
version: 0.12.2
summary: Attack surface detector that identifies endpoints by static analysis.
description: |
  Noir is your ally in the quest for digital fortification. 
  A cutting-edge attack surface detector, it unveils hidden endpoints through meticulous static analysis.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
license: MIT

apps:
  noir:
    command: bin/noir

parts:
  noir:
    source: ./
    plugin: nil #crystal
    #crystal-channel: latest/stable
    override-build: |
      sudo snap install crystal --classic
      snapcraftctl pull
      shards install
      shards build --release
      snapcraftctl build
    build-packages:
      - git
      - libssl-dev
      - libxml2-dev
      - libz-dev
      - libyaml-dev
      - libpcre2-8
    stage-packages:
      - libssl1.1
      - libxml2
