name: noir
base: core24
version: "0.24.0"
summary: Attack surface detector that identifies endpoints by static analysis.
description: |
  Noir is an open-source project specializing in identifying attack surfaces for enhanced whitebox security testing and security pipeline.
  This includes the capability to discover API endpoints, web endpoints, and other potential entry points within source code for thorough security analysis.

grade: stable
confinement: strict
license: MIT

apps:
  noir:
    command: bin/noir
    plugs:
      - home
      - removable-media
      - network
      - network-bind

parts:
  noir:
    source: ./
    plugin: nil
    override-build: |
      git clone https://github.com/crystal-lang/shards.git --branch v0.18.0 --depth 1
      cd shards
      make CRFLAGS="--release"
      export PATH="$PWD/bin:$PATH"
      cd ..

      shards update
      shards install
      crystal build src/noir.cr -o bin/noir --release --no-debug

      install -Dm755 bin/noir "${CRAFT_PART_INSTALL}/bin/noir"
      craftctl default
    build-packages:
      - git
      - crystal
      - make
      - libssl-dev
      - libxml2-dev
      - libz-dev
      - libyaml-dev
      - libpcre2-dev
      - libevent-dev
      - libgmp-dev
      - libpcre3-dev
    stage-packages:
      - libssl3
      - libxml2
      - libevent-2.1-7
