---
    name: DeadLink
    # Controls when the workflow will run
    on:
      # Allows you to run this workflow manually from the Actions tab
      workflow_dispatch:
    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
    jobs:
      # This workflow contains a single job called "build"
      build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
    
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          - name: Find Broken Link
            uses: hahwul/deadfinder@1.4.3
            id: broken-link
            with:
              command: sitemap
              target: https://owasp-noir.github.io/noir/sitemap.xml
          - name: Create an issue
            uses: dacbd/create-issue-action@main
            with:
              token: ${{ github.token }}
              title: DeadLink Issue
              body: |
                ```json
                ${{ steps.broken-link.outputs.output }}
                ```